#!/bin/sh

set -e

CUR=`pwd`

git log > changelog.txt

pdflatex ant
bibtex ant
pdflatex ant
pdflatex ant
pdflatex ant

cd ..
tar jcvf ant.tar.bz2 ant/*.tex ant/*.sty ant/*.bib ant/*.eps ant/*.png ant/mirror ant/update ant/index.html  ant/.git
mv ant.tar.bz2 $CUR

