#!/bin/sh

pdflatex ant.tex
pdflatex ant.tex
bibtex  ant
pdflatex ant.tex
pdflatex ant.tex

git commit -a -v
git push

rsync -avxLH ./ wstein@sage.math.washington.edu:www/books/ant/

ssh wstein@sage.math.washington.edu "cd www/books/ant; latex2html ant >/dev/null&"
